seed: 3435
train_steps: 50000
valid_steps: 1000
save_checkpoint_steps: 1000
keep_checkpoint: 50
report_every: 10

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
transformer_ff: 2048
heads: 8
# share/unshare preprocessing
share_embeddings: 'true'
share_decoder_embeddings: 'true'

optim: adam
adam_beta1: 0.9
adam_beta2: 0.98
learning_rate: 1.0
decay_method: noam
warmup_steps: 4000
#max_grad_norm: 1.0

batch_type: tokens
normalization: tokens
dropout: 0.3
label_smoothing: 0.1

max_generator_batches: 0

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

model_dtype: fp16
loss_scale: 0  # dynamic scaling
tensorboard: 'true'

# adjust for GPU memory
accum_count: 1
batch_size: 6144
world_size: 1
gpu_ranks:
- 0

